language: node_js

node_js:
 - 4
 - 5
 - 6
 - 7

os:
  - linux
  - osx

env:
  - BABEL_ENV=$TRAVIS_NODE_VERSION

cache:
  directories:
    - node_modules

after_success:
  - curl -Lo travis_after_all.py https://git.io/travis_after_all
  - python travis_after_all.py
  - export $(cat .to_export_back) > /dev/null
  - npm run coverage
  - npm run codeclimate
  - BABEL_ENV=v4 npm run compile -- -d lib
  - BABEL_ENV=v5 npm run compile -- -d lib/node5
  - BABEL_ENV=v6 npm run compile -- -d lib/node6
  - BABEL_ENV=v7 npm run compile -- -d lib/node7
  - BABEL_ENV=browsers npm run compile -- -d lib/browsers
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
    - "/^greenkeeper-.+/"
