language: node_js

node_js:
 - 7
 - 6
 - 4

env:
  - BABEL_ENV=development

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

before_script:
  - npm prune

before_deploy:
  - npm install semantic-release
  - npm install codeclimate-test-reporter

  - npm run coverage -- --coverage-report=text-lcov | codeclimate-test-reporter

  - BABEL_ENV=v4 npm run compile -- -d build/node4
  - BABEL_ENV=v6 npm run compile -- -d build/node6
  - BABEL_ENV=v7 npm run compile -- -d build/node7
  - BABEL_ENV=browsers npm run compile -- -d build/browsers

deploy:
  skip_cleanup: true
  provider: script
  script: semantic-release pre && npm publish && semantic-release post || true

  on:
    branch: master
    node: 7

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - /^greenkeeper\/.+/
