language: node_js

os:
  - linux
  - osx

matrix:
  include:
  - node: 4
    env: BABEL_ENV=node4
  - node: 5
    env: BABEL_ENV=node5
  - node: 6
    env: BABEL_ENV=node6
  - node: 7
    env: BABEL_ENV=node7

cache:
  directories:
    - node_modules
    - /tmp/npm-package-genrator/test

after_success:
  - curl -Lo travis_after_all.py https://git.io/travis_after_all
  - python travis_after_all.py
  - export $(cat .to_export_back) > /dev/null
  - npm run coverage
  - npm run codeclimate
  - BABEL_ENV=node4 npm run compile -- -d lib
  - BABEL_ENV=node5 npm run compile -- -d lib/node5
  - BABEL_ENV=node6 npm run compile -- -d lib/node6
  - BABEL_ENV=node7 npm run compile -- -d lib/node7
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
    - "/^greenkeeper-.+/"
